### ISSUE TITLE
Random indentities used for Icam? One or many?

### ISSUE THREAD

**Issue by hengfei-wang** [FreedomGu/DiffPortrait3D#3]
Hi,

Thank you for releasing the code.

I am confused by the setting of Icam. The paper said 

> Herein, appearance leakage from the view condition image will be reflected on the novel view synthesis during inference. This artifact is more pronounced when Iref and Icam exhibit distinct appearance features.

and

> "Instead, we utilize a portrait image from a distinct random identity as the view condition, and generate novel-view images that mirror the head pose as in the condition portrait Icam."

Do you control the identity of Icam? Or simply generate Icam with random identities in training?

Thanks.

**Comment by FreedomGu** [comment]
Hey, Thanks for the question.

During training, we generate lcam with random identities from synthetic datasets.

**Comment by hengfei-wang** [comment]
Thanks for the reply. 
Do you have the plan of releasing the training code?

**Comment by FreedomGu** [comment]
Yes! will publish soon.
